dtype: sbs
min_region_size: 100
region_size: 10000

genome:
  fasta: /Users/allen/genomes/hg38/hg38.fa
  chromsizes: annotations/hg38.mainchroms.sizes
  mutation_rate_file: annotations/mutation-rate.hg38.bedgraph.gz
  blacklist: annotations/blacklist_method12_v1_comb_sort_merged.bed.gz

pipeline_params:
  liftover_chain: annotations/hg19ToHg38.over.chain.gz
  hg38_full_chromsizes: annotations/hg38.allchroms.txt
  replication_strand: annotations/replication-strand.hg38.bed.gz
  gc_content: annotations/at_gc_ratio.hg38.bed.gz
  repeat_masker_fraction: annotations/hg38.repeat_masker_fraction.bed.gz

sample_params:
  cluster: false